name: CI

on:
- push

jobs:
  run-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run:
        ./gradlew test -Dtestcontainers=true
    - name: Run test v2
      run:
        ./gradlew test -Dtestcontainers=true -Dv2=true